WhatsApp/stickers

iOS/README.md

Fixed dead link on ios readme

---

Android/app/src/main/AndroidManifest.xml
Android/app/src/main/java/com/example/samplestickerapp/EntryActivity.java
Android/app/src/main/java/com/example/samplestickerapp/StickerApplication.java

This addresses issue #265 
Fresco initialization was being done on `EntryActivity.java`, so moving it to the application solves the issue.

Moved Fresco initialization to application.

---

README.md
iOS/README.md

Hey,
I have updated the `README` to look more organized.
Changes I have made:
- Corrected spelling
- Moved the iOS notice to the iOS `README`
- Added a Stack Overflow link to point users who need help there instead of the issue page
- Linked the license notice at the bottom to the `LICENSE` file (the link always goes to the current version on GitHub)
- Highlighted filenames
- Made an extra chapter for "Issues", as we already have one for "Pull Requests" (I used the text that was previously in the "MUST READ" chapter and reformatted it to a step by step list)
- Changed the "assign issues to" to "mention .. in the issue" (users without write permission cannot assign other users to an issue)
@simonzhexu @amrit-1901

README update: Grammar and styling

---

iOS/README.md

README update: Proper noun fix

---

Android/app/src/main/java/com/example/samplestickerapp/StickerPackValidator.java

Fixed a minor typo in StickerPackValidator.java

Fixed a minor typo

---

Android/app/src/main/java/com/example/samplestickerapp/StickerPackValidator.java

Revert "Fixed a minor typo"

---

Android/README.md

**The problem**  
some people would like to understand how to expose internal or external files in ContentProvider
**Prerequisites**
I have completed the CLA: Yes

add instructions on how to expose internal or external files

---

Android/app/build.gradle

Making changes to resolve the problem describe in issue #464
Closes #464

Update default application id exception message

---

Android/build.gradle

This updates the Android Gradle Plugin to the latest version.

Bump Android Gradle Plugin to 3.4.1

---

Android/app/build.gradle

This updates the Fresco library to the latest version.

Bump Fresco library to 2.0.0

---

Android/app/build.gradle
Android/app/src/main/java/com/example/samplestickerapp/BaseActivity.java
Android/app/src/main/java/com/example/samplestickerapp/Sticker.java
Android/app/src/main/java/com/example/samplestickerapp/StickerPack.java
Android/app/src/main/java/com/example/samplestickerapp/StickerPackListActivity.java
Android/app/src/main/java/com/example/samplestickerapp/StickerPackListAdapter.java
Android/app/src/main/java/com/example/samplestickerapp/StickerPackListItemViewHolder.java
Android/app/src/main/java/com/example/samplestickerapp/StickerPackLoader.java
Android/app/src/main/java/com/example/samplestickerapp/StickerPackValidator.java
Android/app/src/main/java/com/example/samplestickerapp/StickerPreviewViewHolder.java
Android/app/src/main/java/com/example/samplestickerapp/WhitelistCheck.java

Fixed some warning messages to improve code efficiency.

[Android] Fixed lint warnings

---

Android/app/build.gradle

Fixed `Unresolved reference: JavaVersion.VERSION_1_8` error shown in Android Studio project structure.

Fixed unresolved reference error

---

Android/app/src/main/res/layout/sticker_image.xml
Android/app/src/main/res/values/styles.xml

1. Removed **redundant** progress bar in `sticker_image.xml` layout.
2. Removed some unused resources in `styles.xml` file.

[Android] Removed unused resources

---

Android/app/src/main/res/values-nl/strings.xml

[Android] Improve Dutch translation.

---

Android/app/build.gradle

- Enabled `shrinkResources` - Removes unused code and resources from the packaged app (apk).
- Changed default proguard file to `proguard-android-optimize.txt` - Proguard optimizations make the app size smaller and run faster.

[Android] Enabled shrinking

---

Android/app/src/main/res/values-az/strings.xml
Android/app/src/main/res/values-ca/strings.xml
Android/app/src/main/res/values-en/strings.xml
Android/app/src/main/res/values-ga/strings.xml
Android/app/src/main/res/values-ta/strings.xml

- Fixed incorrect `app name` in some translations.
- Fixed incomplete translation error (Added missing Irish(ga) translation).

[Android] Update strings

---

Android/build.gradle

This updates Android Gradle Plugin to the latest version

Bump Android Gradle Plugin to 3.5.1

---

Android/app/build.gradle

Fixed typo in build.gradle file (universalApk comment)

[Android] Fix typo in build.gradle file

---

Android/app/build.gradle

Updated fresco library to the latest version.

Bump Fresco library to 2.1.0

---

Android/build.gradle

Updated to the latest version of Android Gradle Plugin

Bump Android Gradle Plugin to 3.5.3

---

Android/app/build.gradle
Android/app/src/main/java/com/example/samplestickerapp/StickerPackValidator.java
Android/build.gradle
Android/gradle/wrapper/gradle-wrapper.properties

Updated Gradle Plugin, Fresco, and Material Components to the latest version.

[Android] Update dependencies

---

Android/app/src/main/java/com/example/samplestickerapp/AddStickerPackActivity.java
Android/app/src/main/java/com/example/samplestickerapp/StickerPreviewAdapter.java

Fixed issue : 1 ) After previewed sticker in expanded mode selected sticker gone invisible.
2 ) Changed URL of WhatsApp Play Store Page.

Prevent sticker hide on expanded view.

---

Android/app/build.gradle
Android/build.gradle

Fix for #777
* Migrate to mavenCentral from jcenter.
* Updated fresco version to 2.3.0 (Because when migrate to mavenCentral can't able to find version 2.2.0 issue arise).

Migrate to mavenCentral from jcenter.

---

Android/app/src/main/res/values-gl/strings.xml

Added Galician translations for Android.

[Android] Add Galician translations

---

Android/app/build.gradle
Android/app/src/main/AndroidManifest.xml
Android/build.gradle
Android/gradle.properties
Android/gradle/wrapper/gradle-wrapper.properties

https://github.com/user-attachments/assets/38131533-21a4-429e-85c5-0328701e4a86

Gradle update

---

iOS/README.md
iOS/WAStickersThirdParty/Sticker.swift

Update accessibility text character limit definition

Update accessibility text limit control

---

Android/README.md
Android/app/src/main/assets/contents.json
Android/app/src/main/java/com/example/samplestickerapp/ContentFileParser.java
Android/app/src/main/java/com/example/samplestickerapp/Sticker.java
Android/app/src/main/java/com/example/samplestickerapp/StickerContentProvider.java
Android/app/src/main/java/com/example/samplestickerapp/StickerPackLoader.java
Android/app/src/main/java/com/example/samplestickerapp/StickerPackValidator.java

Added accessibility field text to json file, and support to export to wa

A11 y text
